[package]
name = "holo"
version = "0.3.0"
edition = "2024"
description = "A terminal UI for Android developers"
license = "MIT"
repository = "https://github.com/measure-sh/holo"
homepage = "https://github.com/measure-sh/holo"
keywords = ["android", "adb", "tui", "terminal"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
color-eyre = "0.6"
chrono = "0.4.44"
tui-textarea = { version = "0.7", features = ["crossterm"] }
open = "5.3.3"
dirs = "6"
arboard = { version = "3.6.1", default-features = false }
serde_json = "1.0.149"
